%package -n patterns-sailfish-device-configuration-h4413
Summary: Jolla Configuration h4413
Requires: patterns-sailfish-device-configuration-common-h4413
Requires: patterns-sailfish-device-adaptation-voyager

Requires: droid-config-h4413-sailfish
Requires: droid-config-h4413-pulseaudio-settings
Requires: droid-config-h4413-policy-settings
Requires: droid-config-h4413-preinit-plugin
Requires: droid-config-h4413-flashing
Requires: droid-config-h4413-bluez5
Requires: droid-hal-version-h4413

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-system-flashlight
Requires: jolla-settings-networking-multisim

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-h4413
Pattern with packages for h4413 configurations

%files -n patterns-sailfish-device-configuration-h4413
