%package -n patterns-sailfish-device-configuration-h4113
Summary: Jolla Configuration h4113
Requires: patterns-sailfish-device-configuration-common-h4113
Requires: patterns-sailfish-device-adaptation-pioneer

Requires: droid-config-h4113-sailfish
Requires: droid-config-h4113-pulseaudio-settings
Requires: droid-config-h4113-policy-settings
Requires: droid-config-h4113-preinit-plugin
Requires: droid-config-h4113-flashing
Requires: droid-config-h4113-bluez5
Requires: droid-hal-version-h4113

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-system-flashlight
Requires: jolla-settings-networking-multisim

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-h4113
Pattern with packages for h4113 configurations

%files -n patterns-sailfish-device-configuration-h4113
