%package -n patterns-sailfish-device-configuration-h3413
Summary: Jolla Configuration h3413
Requires: patterns-sailfish-device-configuration-common-h3413
Requires: patterns-sailfish-device-adaptation-voyager

Requires: droid-config-h3413-sailfish
Requires: droid-config-h3413-pulseaudio-settings
Requires: droid-config-h3413-policy-settings
Requires: droid-config-h3413-preinit-plugin
Requires: droid-config-h3413-flashing
Requires: droid-config-h3413-bluez5
Requires: droid-hal-version-h3413

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-h3413
Pattern with packages for h3413 configurations

%files -n patterns-sailfish-device-configuration-h3413
