%package -n patterns-sailfish-device-configuration-h4213
Summary: Jolla Configuration h4213
Requires: patterns-sailfish-device-configuration-common-h4213
Requires: patterns-sailfish-device-adaptation-discovery

Requires: droid-config-h4213-sailfish
Requires: droid-config-h4213-pulseaudio-settings
Requires: droid-config-h4213-policy-settings
Requires: droid-config-h4213-preinit-plugin
Requires: droid-config-h4213-flashing
Requires: droid-config-h4213-bluez5
Requires: droid-hal-version-h4213

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-system-flashlight
Requires: jolla-settings-networking-multisim

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-h4213
Pattern with packages for h4213 configurations

%files -n patterns-sailfish-device-configuration-h4213
