%package -n patterns-sailfish-device-configuration-h3213
Summary: Jolla Configuration h3213
Requires: patterns-sailfish-device-configuration-common-h3213
Requires: patterns-sailfish-device-adaptation-discovery

Requires: droid-config-h3213-sailfish
Requires: droid-config-h3213-pulseaudio-settings
Requires: droid-config-h3213-policy-settings
Requires: droid-config-h3213-preinit-plugin
Requires: droid-config-h3213-flashing
Requires: droid-config-h3213-bluez5
Requires: droid-hal-version-h3213

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-h3213
Pattern with packages for h3213 configurations

%files -n patterns-sailfish-device-configuration-h3213
